// <auto-generated />
using System;
using Jiten.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jiten.Core.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260324164425_Srs")]
    partial class Srs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiKey_Hash");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiKey_UserId");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("IX_ApiKey_UserId_IsRevoked");

                    b.ToTable("ApiKeys", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.Authentication.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.Authentication.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("RateLimitTier")
                        .HasColumnType("integer");

                    b.Property<bool>("ReceivesNewsletter")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("TosAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.FSRS.FsrsCard", b =>
                {
                    b.Property<long>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CardId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Due")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastReview")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("ReadingIndex")
                        .HasColumnType("smallint");

                    b.Property<double?>("Stability")
                        .HasColumnType("double precision");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("Step")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.HasKey("CardId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "State", "Due")
                        .HasDatabaseName("IX_FsrsCard_UserId_State_Due");

                    b.HasIndex("UserId", "WordId", "ReadingIndex")
                        .IsUnique();

                    b.ToTable("FsrsCards", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.FSRS.FsrsReviewLog", b =>
                {
                    b.Property<long>("ReviewLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReviewLogId"));

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewDuration")
                        .HasColumnType("integer");

                    b.HasKey("ReviewLogId");

                    b.HasIndex("CardId", "ReviewDateTime")
                        .IsUnique();

                    b.ToTable("FsrsReviewLogs", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.User.UserFsrsSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("DesiredRetention")
                        .HasColumnType("double precision");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.HasKey("UserId");

                    b.ToTable("UserFsrsSettings", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.User.UserStudyDeck", b =>
                {
                    b.Property<int>("UserStudyDeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserStudyDeckId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeckId")
                        .HasColumnType("integer");

                    b.Property<int>("DeckType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DownloadType")
                        .HasColumnType("integer");

                    b.Property<bool>("ExcludeKana")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxFrequency")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxGlobalFrequency")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("integer");

                    b.Property<int>("MinFrequency")
                        .HasColumnType("integer");

                    b.Property<int?>("MinGlobalFrequency")
                        .HasColumnType("integer");

                    b.Property<int?>("MinOccurrences")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PosFilter")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<float?>("TargetPercentage")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserStudyDeckId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserStudyDeck_UserId");

                    b.HasIndex("UserId", "DeckId")
                        .IsUnique()
                        .HasFilter("\"DeckId\" IS NOT NULL");

                    b.ToTable("UserStudyDecks", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.User.UserStudyDeckWord", b =>
                {
                    b.Property<int>("UserStudyDeckId")
                        .HasColumnType("integer");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.Property<short>("ReadingIndex")
                        .HasColumnType("smallint");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("UserStudyDeckId", "WordId", "ReadingIndex");

                    b.HasIndex("UserStudyDeckId", "Occurrences")
                        .IsDescending(false, true);

                    b.HasIndex("UserStudyDeckId", "SortOrder");

                    b.ToTable("UserStudyDeckWords", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserAccomplishment", b =>
                {
                    b.Property<int>("AccomplishmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccomplishmentId"));

                    b.Property<int>("CompletedDeckCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MediaType")
                        .HasColumnType("integer");

                    b.Property<long>("TotalCharacterCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalWordCount")
                        .HasColumnType("bigint");

                    b.Property<int>("UniqueKanjiCount")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueWordCount")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueWordUsedOnceCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AccomplishmentId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserAccomplishment_UserId");

                    b.HasIndex("UserId", "MediaType")
                        .IsUnique()
                        .HasDatabaseName("IX_UserAccomplishment_UserId_MediaType");

                    b.ToTable("UserAccomplishments", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserCoverage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<double>("Coverage")
                        .HasColumnType("double precision");

                    b.Property<double>("UniqueCoverage")
                        .HasColumnType("double precision");

                    b.HasKey("UserId", "DeckId")
                        .HasName("PK_UserCoverages");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserCoverage_UserId");

                    b.ToTable("UserCoverages", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserCoverageChunk", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<short>("Metric")
                        .HasColumnType("smallint");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<short[]>("Values")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.HasKey("UserId", "Metric", "ChunkIndex")
                        .HasName("PK_UserCoverageChunks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserCoverageChunks_UserId");

                    b.ToTable("UserCoverageChunks", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserDeckPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "DeckId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserDeckPreference_UserId");

                    b.HasIndex("UserId", "IsFavourite")
                        .HasDatabaseName("IX_UserDeckPreference_UserId_IsFavourite");

                    b.HasIndex("UserId", "IsIgnored")
                        .HasDatabaseName("IX_UserDeckPreference_UserId_IsIgnored");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_UserDeckPreference_UserId_Status");

                    b.ToTable("UserDeckPreferences", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserKanjiGrid", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("KanjiScoresJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("LastComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserKanjiGrids", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserMetadata", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CoverageDirty")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CoverageDirtyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CoverageRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserMetadatas", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles", "user");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserWordSetState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "SetId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserWordSetState_UserId");

                    b.ToTable("UserWordSetStates", "user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "user");
                });

            modelBuilder.Entity("ApiKey", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", "User")
                        .WithOne()
                        .HasForeignKey("ApiKey", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jiten.Core.Data.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jiten.Core.Data.FSRS.FsrsCard", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.FSRS.FsrsReviewLog", b =>
                {
                    b.HasOne("Jiten.Core.Data.FSRS.FsrsCard", "Card")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Jiten.Core.Data.User.UserFsrsSettings", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithOne()
                        .HasForeignKey("Jiten.Core.Data.User.UserFsrsSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.User.UserStudyDeck", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.User.UserStudyDeckWord", b =>
                {
                    b.HasOne("Jiten.Core.Data.User.UserStudyDeck", "StudyDeck")
                        .WithMany("Words")
                        .HasForeignKey("UserStudyDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyDeck");
                });

            modelBuilder.Entity("Jiten.Core.Data.UserAccomplishment", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.UserCoverage", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.UserCoverageChunk", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.UserDeckPreference", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.UserKanjiGrid", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithOne()
                        .HasForeignKey("Jiten.Core.Data.UserKanjiGrid", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.UserMetadata", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithOne()
                        .HasForeignKey("Jiten.Core.Data.UserMetadata", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.UserProfile", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithOne()
                        .HasForeignKey("Jiten.Core.Data.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.UserWordSetState", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Jiten.Core.Data.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jiten.Core.Data.FSRS.FsrsCard", b =>
                {
                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("Jiten.Core.Data.User.UserStudyDeck", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
